Repository cisagov/ScubaGoggles, pull requests merged in 2024-08, with the labels that each got.

#315 Changes to Common Controls Baseline
  Testing/RegoTests/commoncontrols/commoncontrols06_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols10_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols16_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols17_test.rego
  baselines/Common Controls Minimum Viable Secure Configuration Baseline v0.2.md
  drift-rules/GWS Drift Monitoring Rules - Common Controls as of 11-14-23.csv
  rego/Commoncontrols.rego
  scubagoggles/provider.py
Labels: Common Controls, Baseline Revision, High, Code Changes Required

#333 Orchestrator: convert to class implementation (issue 167)
  scubagoggles/main.py
  scubagoggles/orchestrator.py
Labels: enhancement

#338 Implement Gmail 19.2 and 19.3 in rego
  Testing/RegoTests/gmail/gmail19_test.rego
  rego/Gmail.rego
Labels: bug

#343 [#328] Default Safe variable is incorrect in many cases
  Testing/RegoTests/calendar/calendar01_test.rego
  Testing/RegoTests/calendar/calendar02_test.rego
  Testing/RegoTests/calendar/calendar03_test.rego
  Testing/RegoTests/calendar/calendar04_test.rego
  Testing/RegoTests/chat/chat01_test.rego
  Testing/RegoTests/chat/chat03_test.rego
  Testing/RegoTests/classroom/classroom01_test.rego
  Testing/RegoTests/classroom/classroom04_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols05_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols11_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols15_test.rego
  Testing/RegoTests/drive/drive01_test.rego
  Testing/RegoTests/drive/drive02_test.rego
  Testing/RegoTests/drive/drive03_test.rego
  Testing/RegoTests/gmail/gmail05_test.rego
  Testing/RegoTests/gmail/gmail06_test.rego
  Testing/RegoTests/gmail/gmail07_test.rego
  Testing/RegoTests/gmail/gmail08_test.rego
  Testing/RegoTests/gmail/gmail12_test.rego
  Testing/RegoTests/gmail/gmail13_test.rego
  Testing/RegoTests/gmail/gmail14_test.rego
  Testing/RegoTests/gmail/gmail15_test.rego
  Testing/RegoTests/groups/groups01_test.rego
  Testing/RegoTests/groups/groups02_test.rego
  Testing/RegoTests/groups/groups03_test.rego
  Testing/RegoTests/groups/groups06_test.rego
  Testing/RegoTests/meet/meet04_test.rego
  Testing/RegoTests/meet/meet05_test.rego
  rego/Calendar.rego
  rego/Chat.rego
  rego/Classroom.rego
  rego/Commoncontrols.rego
  rego/Drive.rego
  rego/Gmail.rego
  rego/Groups.rego
  rego/Meet.rego
Labels: Code review

#346 Add Omit to the Summary Counts
  scubagoggles/reporter/reporter.py
Labels: enhancement

#336 Add functional smoke tests and automated testing workflow
  .github/actions/setup-dependencies-macos/action.yml
  .github/actions/setup-dependencies-windows/action.yml
  .github/workflows/pylint.yml
  .github/workflows/run_smoke_test.yml
  Testing/Functional/SmokeTests/selenium_browser.py
  Testing/Functional/SmokeTests/smoke_test.py
  Testing/Functional/SmokeTests/smoke_test_utils.py
  Testing/Functional/conftest.py
  pytest.ini
  scubagoggles/utils.py
Labels: improvement, testing

#354 Rename the baseline markdown files
  baselines/README.md
  baselines/calendar.md
  baselines/chat.md
  baselines/classroom.md
  baselines/commoncontrols.md
  baselines/drive.md
  baselines/gmail.md
  baselines/groups.md
  baselines/meet.md
  baselines/sites.md
  docs/authentication/OAuth.md
  scubagoggles/reporter/md_parser.py
  scubagoggles/reporter/reporter.py
Labels: enhancement

#367 Remove synchronize type from smoke test
  .github/workflows/run_smoke_test.yml
Labels: bug
