Repository cisagov/ScubaGoggles, pull requests merged in 2024-09, with the labels that each got.

#369 Correct the "No Such Event" behavior for Gmail policies with multiple settings
  Testing/RegoTests/gmail/gmail05_test.rego
  Testing/RegoTests/gmail/gmail07_test.rego
  rego/Gmail.rego
Labels: bug

#356 update supported Python version
  docs/installation/DownloadAndInstall.md
  requirements.txt
  scubagoggles/provider.py
  scubagoggles/reporter/reporter.py
  scubagoggles/scuba_constants.py
  setup.py
Labels: bug

#389 Switched Security to Secure Across All Baselines
  README.md
  baselines/calendar.md
  baselines/chat.md
  baselines/classroom.md
  baselines/commoncontrols.md
  baselines/drive.md
  baselines/gmail.md
  baselines/groups.md
  baselines/meet.md
  baselines/sites.md
Labels: Baseline Revision, High

#394 [#294, #295] Update Gmail policies 5 and 7 to include all instances of spoofing and authentication settings that are not complaint
  Testing/RegoTests/gmail/gmail05_test.rego
  Testing/RegoTests/gmail/gmail07_test.rego
  rego/Gmail.rego
Labels: Gmail, Code review

#401 Updated instructions for Classroom1.2
  baselines/classroom.md
Labels: Google Classroom, Baseline Revision

#405 Revert "Updated instructions for Classroom1.2 (#401)"
  baselines/classroom.md
Labels: Baseline Revision

#413 Add config file support for existing parameters
  .github/workflows/pylint.yml
  README.md
  docs/usage/Config.md
  docs/usage/Examples.md
  docs/usage/Parameters.md
  requirements.txt
  sample-config-files/basic_config.yaml
  scubagoggles/main.py
  scubagoggles/scuba_argument_parser.py
  setup.py
Labels: enhancement

#416 Add support for user input and documentation improvements to smoke testing workflow
  .github/actions/setup-dependencies-macos/action.yml
  .github/actions/setup-dependencies-windows/action.yml
  .github/workflows/run_smoke_test.yml
  Testing/Functional/SmokeTests/README.md
  Testing/Functional/SmokeTests/selenium_browser.py
  Testing/Functional/SmokeTests/smoke_test.py
  Testing/Functional/SmokeTests/smoke_test_utils.py
  Testing/Functional/conftest.py
Labels: bug, enhancement

#436 Update DownloadAndInstall.md
  docs/installation/DownloadAndInstall.md
Labels: documentation
