Repository cisagov/ScubaGoggles, pull requests merged in 2024-10, with the labels that each got.

#445 Clarifying Implementation Steps of CommonControls13.1
  baselines/classroom.md
  baselines/commoncontrols.md
Labels: Internal Discussion, Baseline Revision

#471 [#395] Update Calendar policy 4.1 to detect inherited settings
  rego/Calendar.rego
  scubagoggles/provider.py
Labels: Code review

#478 Implement new password policy
  Testing/RegoTests/commoncontrols/commoncontrols05_test.rego
  rego/Commoncontrols.rego
Labels: enhancement

#485 Implement data processing policy for common controls
  Testing/RegoTests/commoncontrols/commoncontrols15_test.rego
  rego/Commoncontrols.rego
  scubagoggles/provider.py
Labels: enhancement
