Repository cisagov/ScubaGoggles, pull requests merged in 2024-02, with the labels that each got.

#163 Enhance Error handling
  Testing/RegoTests/gmail/gmail03_test.rego
  Testing/RegoTests/gmail/gmail10_test.rego
  Testing/RegoTests/gmail/gmail15_test.rego
  Testing/RegoTests/gmail/gmail16_test.rego
  Testing/RegoTests/gmail/gmail18_test.rego
  rego/Commoncontrols.rego
  rego/Gmail.rego
  rego/Groups.rego
  scubagoggles/orchestrator.py
  scubagoggles/provider.py
  scubagoggles/reporter/reporter.py
  scubagoggles/reporter/scripts/main.js
  scubagoggles/types.py
Labels: enhancement

#182 Add missing step to service account creation instructions
  README.md
Labels: documentation

#150 Addressed All Comments for Common Controls made by SNL for RFC
  Testing/RegoTests/commoncontrols/commoncontrols06_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols07_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols08_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols09_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols10_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols11_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols12_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols13_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols14_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols15_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols16_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols17_test.rego
  Testing/RegoTests/commoncontrols/commoncontrols18_test.rego
  Testing/RegoTests/rules/rules01_test.rego
  Testing/run_unit_tests.py
  baselines/Common Controls Minimum Viable Secure Configuration Baseline v0.1.md
  drift-rules/GWS Drift Monitoring Rules - Common Controls as of 11-14-23.csv
  rego/Commoncontrols.rego
  rego/Rules.rego
Labels: Baseline Revision, High

#180 Added ScubaGoggles Not Found Error to ReadME
  README.md
Labels: documentation

#162 Fixed DRIVEDOCS.6.1v0.1 Implementation Steps per 159
  baselines/Google Drive and Docs Minimum Viable Secure Configuration Baseline v0.1.md
Labels: Baseline Revision, High, Code Changes Required

#183 Changed DRIVEDOCS.1.3v0.1 to SHALL per RFC Comment 178
  baselines/Google Drive and Docs Minimum Viable Secure Configuration Baseline v0.1.md
  rego/Drive.rego
Labels: Baseline Revision, High, Code Changes Required

#188 SPF Baseline Revision
  Testing/RegoTests/gmail/gmail03_test.rego
  baselines/Gmail Minimum Viable Secure Configuration Baseline v0.1.md
  rego/Gmail.rego
Labels: Baseline Revision

#204 Calendar group settings fix
  Testing/RegoTests/calendar/calendar01_test.rego
  Testing/RegoTests/calendar/calendar02_test.rego
  Testing/RegoTests/chat/chat01_test.rego
  Testing/RegoTests/chat/chat02_test.rego
  Testing/RegoTests/chat/chat03_test.rego
  Testing/RegoTests/chat/chat04_test.rego
  Testing/RegoTests/chat/chat05_test.rego
  rego/Calendar.rego
  rego/Chat.rego
  rego/Utils.rego
Labels: bug, enhancement

#206 Correct summary test counts for rules and common controls
  scubagoggles/orchestrator.py
Labels: bug
