Repository cisagov/ScubaGoggles, pull requests merged in 2024-05, with the labels that each got.

#245 Resolve Groups 7.1 dependency issue with Groups 6.1
  Testing/RegoTests/groups/groups07_test.rego
  rego/Groups.rego
  rego/Utils.rego
  scubagoggles/provider.py
Labels: bug, Code review

#270 Remove calls to old FilterEvents function
  rego/Chat.rego
  rego/Classroom.rego
  rego/Meet.rego
Labels: bug

#279 Detailed report message for GWS.CHAT.7
  Testing/RegoTests/chat/chat07_test.rego
  rego/Chat.rego
Labels: bug, enhancement

#293 Baseline Review
  baselines/Common Controls Minimum Viable Secure Configuration Baseline v0.1.md
  baselines/Gmail Minimum Viable Secure Configuration Baseline v0.1.md
  baselines/Google Calendar Minimum Viable Secure Configuration Baseline v0.1.md
  baselines/Google Chat Minimum Viable Secure Configuration Baseline v0.1.md
  baselines/Google Drive and Docs Minimum Viable Secure Configuration Baseline v0.1.md
Labels: Baseline Revision
