Repository cisagov/ScubaGoggles, pull requests merged in 2025-05, with the labels that each got.

#679 Update OAuth Instructions
  docs/authentication/OAuth.md
  docs/authentication/ServiceAccount.md
Labels: bug, documentation, eel

#688 Update Rego Prereqs for Chat, Calendar, Classroom, and Groups
  scubagoggles/provider.py
  scubagoggles/rego/Calendar.rego
  scubagoggles/rego/Chat.rego
  scubagoggles/rego/Classroom.rego
  scubagoggles/rego/Commoncontrols.rego
  scubagoggles/rego/Groups.rego
Labels: enhancement

#690 Update Gmail.rego with new prerequisites
  scubagoggles/policy_api.py
  scubagoggles/rego/Commoncontrols.rego
  scubagoggles/rego/Gmail.rego
  scubagoggles/reporter/reporter.py
Labels: Gmail, eel

#684 include omitted evaluation detail to reports
  scubagoggles/reporter/reporter.py
Labels: enhancement

#700 Add missing default values for policy API
  scubagoggles/policy_api.py
Labels: bug

#694 Indicate in the report which tests rely on log events
  docs/usage/Limitations.md
  scubagoggles/reporter/reporter.py
Labels: documentation, enhancement
