Repository cisagov/ScubaGoggles, pull requests merged in 2025-04, with the labels that each got.

#647 Move rules back into common controls
  scubagoggles/Testing/Functional/SmokeTests/smoke_test_utils.py
  scubagoggles/Testing/RegoTests/commoncontrols/commoncontrols13_test.rego
  scubagoggles/Testing/RegoTests/rules/rules01_test.rego
  scubagoggles/Testing/run_unit_tests.py
  scubagoggles/orchestrator.py
  scubagoggles/provider.py
  scubagoggles/rego/Commoncontrols.rego
  scubagoggles/rego/Rules.rego
  scubagoggles/reporter/IndividualReport/AlertsDescriptions.json
  scubagoggles/reporter/IndividualReport/IndividualReportTemplate.html
  scubagoggles/reporter/reporter.py
  scubagoggles/reporter/scripts/main.js
  scubagoggles/reporter/styles/main.css
  scubagoggles/sample-report/BaselineReports.html
  scubagoggles/sample-report/IndividualReports/CommoncontrolsReport.html
  scubagoggles/sample-report/IndividualReports/RulesReport.html
  scubagoggles/scuba_argument_parser.py
Labels: enhancement

#652 Update Reference to Common Controls in DriveDocs
  scubagoggles/baselines/drive.md
Labels: Drive_Docs, Baseline Revision

#651 Fix Tenant Table Check in Smoke Test
  scubagoggles/Testing/Functional/SmokeTests/selenium_browser.py
  scubagoggles/Testing/Functional/SmokeTests/smoke_test_utils.py
Labels: bug

#674 Upgrade Ubuntu Runner & Python Versions in Pylint Workflow
  .github/workflows/pylint.yml
Labels: bug

#670 Default Missing Service Status Settings to DISABLED
  scubagoggles/policy_api.py
Labels: bug, eel

#682 Update prereqs for Sites and Meet
  scubagoggles/provider.py
  scubagoggles/rego/Meet.rego
  scubagoggles/rego/Sites.rego
Labels: enhancement

#683 Update drive prereqs
  scubagoggles/rego/Drive.rego
Labels: enhancement

#685 [#610] Update policy 10.1
  scubagoggles/Testing/RegoTests/commoncontrols/commoncontrols10_test.rego
  scubagoggles/rego/Commoncontrols.rego
Labels: bug, Common Controls
